mmocr/core/evaluation/ocr_metric.py
requirements/readthedocs.txt
requirements/runtime.txt
setup.cfg

This PR replaces python-Levenshtein with RapidFuzz (disclaimer: I am the author) for the following reasons:
- python-Levenshtein is the only GPL licensed dependency (RapidFuzz is MIT licensed)
- RapidFuzz provides wheels, while this currently requires workarounds like the `Levenshtein` library for python-Levenshtein (This will probably get better once a new maintainer for python-Levenshtein is found)
- The Levenshtein implementation in RapidFuzz is a lot faster:

Replace python-Levenshtein with RapidFuzz

---

README.md
configs/textdet/maskrcnn/README.md
configs/textdet/psenet/README.md
configs/textrecog/crnn/README.md
configs/textrecog/nrtr/README.md
configs/textrecog/robust_scanner/README.md

Add methods to readme

---

tests/test_models/test_detector.py

add unit test for textsnake

---

mmocr/apis/inference.py
tests/test_apis/test_model_inference.py

* mmocr.apis.model_inference now supports a numpy array as input
* Fixes #73

Add support for numpy array inference

---

mmocr/models/textdet/postprocess/wrapper.py

This solves the issue when dealing with documents with a large number of words per-page.
**Note that i haven't test the effect of increasing the candidates on whether it affects the prediction fps or not.**
@jeffreykuang i am not signing the `CLA` license, so close this pull, and a pull under your name for this commit.
```
max_candidates=3000):
```

increase the number of candidates for DBNet to 3000

---

mmocr/datasets/utils/loader.py
tests/test_dataset/test_loader.py

Otherwise, the loader is not compatible with for loop iteration.

Implement iter protocol for Loader

---

mmocr/core/__init__.py
mmocr/datasets/__init__.py
mmocr/models/__init__.py
mmocr/models/common/__init__.py
mmocr/models/kie/__init__.py
mmocr/models/textdet/__init__.py
mmocr/models/textrecog/__init__.py

Previously, functions/objects imported by `from .xxx import *` are not listed in `__all__`. The current writing fixes that.

Add things from "import *" to __all__

---

mmocr/datasets/kie_dataset.py
mmocr/datasets/utils/loader.py
mmocr/models/kie/extractors/sdmgr.py
mmocr/models/textrecog/convertors/base.py
mmocr/utils/__init__.py
mmocr/utils/fileio.py
mmocr/utils/lmdb_util.py
tests/test_utils/test_textio.py
tools/data/textdet/coco_to_line_dict.py
tools/data/textdet/ctw1500_converter.py
tools/data/textdet/icdar_converter.py
tools/data/textrecog/seg_synthtext_converter.py
tools/data/textrecog/svt_converter.py
tools/ocr_test_imgs.py
tools/test_imgs.py

This simplifies code, and avoids direct manipulations of text io.

Add list_from_file and list_to_file

---

MANIFEST.in
requirements/runtime.txt

It seems that the packages in requirements/build.txt will not be installed when using pip and mim.

Fix installing requirements with pip and mim

---

configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py
configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py
mmocr/datasets/kie_dataset.py
mmocr/datasets/pipelines/__init__.py
mmocr/datasets/pipelines/kie_transforms.py

5x speedup
Before:
After:
Fix https://github.com/open-mmlab/mmocr/issues/164
Fix https://github.com/open-mmlab/mmocr/issues/238

Ignore img processing for KIE without visual

---

configs/_base_/recog_datasets/seg_toy_dataset.py
configs/textrecog/crnn/crnn_academic_dataset.py
configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py
configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
configs/textrecog/robust_scanner/robustscanner_r31_academic.py
configs/textrecog/sar/sar_r31_parallel_decoder_academic.py
configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py
configs/textrecog/sar/sar_r31_sequential_decoder_academic.py
configs/textrecog/seg/seg_r31_1by16_fpnocr_academic.py
configs/textrecog/tps/crnn_tps_academic_dataset.py
mmocr/datasets/uniform_concat_dataset.py
tests/test_dataset/test_uniform_concat_dataset.py

Use `uniform_concat_dataset` such that `cfg.data.val` and `cfg.data.test` have attribute `pipeline`.

use unifor_concat_datase instead of concat_dataset

---

tools/train.py

This PR added support for `ConcatDataset` with two workflows. In particular, if one wants to use `workflow = [('train', 1), ('val', 1)]` but in the configuration file there is a `ConcatDataset`, the actual `tools/train.py` is not able to handle it. In this case, as a hotfix, I propose to set the pipeline for each dataset in `datasets`. 
Note: I have seen the new `UniformConcatDataset`'s implementation and in the future I will use this new MMOCR component, but for the people that still continue to use `ConcatDataset`, I suppose this PR could help.

Added support for ConcatDataset with two workflows

---

docs/datasets.md
tools/data/textrecog/synthtext_converter.py

The script is bulit based on the work of @yuexy

Add synthtext converter and update docs

---

docs/datasets.md
docs_zh_CN/datasets.md

Removed TOC because Readthedocs can't link Chinese TOC to its corresponding content

[Docs] fix dead links, remove invalid TOC in CN docs

---

configs/_base_/det_dataset/toy_dataset.py
configs/_base_/recog_datasets/toy_dataset.py
configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py
configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py
configs/textdet/drrg/drrg_r50_fpn_unet_1200e_ctw1500.py
configs/textdet/fcenet/fcenet_r50_fpn_1500e_icdar2015.py
configs/textdet/fcenet/fcenet_r50dcnv2_fpn_1500e_ctw1500.py
configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_ctw1500.py
configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2015.py
configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2017.py
configs/textdet/panet/panet_r18_fpem_ffm_600e_ctw1500.py
configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py
configs/textdet/panet/panet_r50_fpem_ffm_600e_icdar2017.py
configs/textdet/psenet/psenet_r50_fpnf_600e_ctw1500.py
configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py
configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2017.py
configs/textdet/textsnake/textsnake_r50_fpn_unet_1200e_ctw1500.py
configs/textrecog/crnn/crnn_academic_dataset.py
docs/datasets.md
docs_zh_CN/datasets.md
mmocr/datasets/pipelines/loading.py
tools/data/textdet/ctw1500_converter.py
tools/data/textdet/icdar_converter.py
tools/data/textdet/totaltext_converter.py
tools/data/textrecog/totaltext_converter.py

In some OCR datasets, including `ctw1500` and `icdar2017`, there are some images containing orientation info in  EXIF data. The default OpenCV backend used in MMCV would read them and apply the rotation on the images. However, their associated annotations are made on the raw pixels, and such inconsistency leads to wrong examples during training.
In previous versions, we chose to save these images in`.png` format and drop the info in the preprocessing step. MMCV 1.3.8 starts to support `color_ignore_orientation` mode that ignores EXIF info when loading images. (https://github.com/open-mmlab/mmcv/pull/1091) This feature helps remove the extra step that modifies the original dataset in our preprocessing scripts, while it ensures the correctness of the annotations. 
Users are recommended to …

Fix #112: Remove the need of drop_orientation_info in data preprocessing steps

---

tools/kie_test_imgs.py

The "pretrained" parameter in SDMG-R is removed started from MMOCR 0.2.1.

Remove deprecated "pretrained" parameter in kie_test_imgs

---

docker/Dockerfile
docs/install.md
docs_zh_CN/install.md
mmocr/__init__.py

In mmdet 2.13.0, the `__init__()` function of `SingleStageDetector` always assign a value to the `pretrained` variable of the backbone, which could cause an error if the backbone does not accept `pretrained` in its initializer. (https://github.com/open-mmlab/mmdetection/pull/5363). It was fixed in `2.14.0`.
We upgrade the dependency requirement to avoid potential errors.

[Fix] upgrade version requirement of mmdet to 2.14.0 to avoid known bugs

---

docs/demo.md
mmocr/core/visualize.py

- Added the optional argument `out_file` to specify output path to save the visualized image in the `det_recog_show_result` method
- Fixed wrong url in demo.md

Add output option to det_recog_show_result method

---

docs/demo.md
docs_zh_CN/demo.md
mmocr/utils/ocr.py

1. Add box stitching back to ocr.py
2. Add config_dir which allows users to specify the default config path
3. Warn users when overriding parameters are set
4. Allow users to use customized checkpoint files
Fix #397

[Feature] Improve ocr.py

---

configs/_base_/recog_datasets/seg_toy_dataset.py
configs/_base_/recog_datasets/toy_dataset.py
configs/textrecog/crnn/crnn_academic_dataset.py
configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py
configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
configs/textrecog/robust_scanner/robustscanner_r31_academic.py
configs/textrecog/sar/sar_r31_parallel_decoder_academic.py
configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py
configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py
configs/textrecog/sar/sar_r31_sequential_decoder_academic.py
configs/textrecog/seg/seg_r31_1by16_fpnocr_academic.py
configs/textrecog/tps/crnn_tps_academic_dataset.py
mmocr/apis/inference.py
mmocr/core/visualize.py
mmocr/models/textrecog/convertors/seg.py
mmocr/models/textrecog/recognizer/encode_decode_recognizer.py
mmocr/models/textrecog/recognizer/seg_recognizer.py
tests/test_apis/test_model_inference.py
tests/test_models/test_recog_config.py
tests/test_models/test_recognizer.py

support batch inference for all the resize modes in text recognition algorithms, including:
1. Resize to a fix shape;
2. Keep aspect ratio resize and pad to a fix shape; 
3. keep aspect ratio resize, shape is not fixed.
So that `crnn` and `segocr` (keep aspect ratio resize) can use batch inference during testing.  
(Note: There may be a mismatch in eval metric for batch_size=1 and batch_size>1)

support batch inference for crnn and segocr

---

.readthedocs.yml
docs/conf.py
docs_zh_CN/conf.py
requirements/readthedocs.txt

Since the introduction of dependency version checking in `__init__`, the old readthedocs config is no longer valid as it mocks MMCV and MMDetection and hides the version information in these packages. The assertion error blocks `autodoc` from importing modules and generate docs for APIs.
`autodoc_mock_imports` also unnecessarily mocked too many modules and this PR removes them.
Also modified code so that the version of the docs can be in sync with MMOCR.

[Docs] Fix API reference & version, support exporting pdf & epub

---

mmocr/utils/ocr.py
tools/test.py

Some models no longer accept `pretrained` parameter in their constructors and use `init_cfg` to initialize themselves instead. But `test.py` still passes `None` to `pretrained` whichever the model is being tested. So I added a simple check to skip this step. 
Also fixed a linting problem.

Fix #416: Fix undesired assignment to "pretrained" in test.py

---

mmocr/utils/__init__.py
mmocr/utils/model.py
mmocr/utils/ocr.py
tests/test_models/test_detector.py
tests/test_utils/test_model.py
tools/test.py

Fixes #398. 
SyncBN doesn't support CPU inference and can cause some other issues during inference. We add a utility  `revert_sync_batchnorm`, which can convert SyncBN in any model to BN. It's only used in our inference scripts.
PyTorch provides an implementation of `convert_sync_batchnorm` which converts `BatchNorm1D`, `BatchNorm2D` and `BatchNorm3D` to `SyncBatchNorm`. However, it doesn't provide an inverse function for that. The reason is `SyncBatchNorm` neither has a strict input dimension checking nor stores the expected input dimension, whereas BatchNormxD strictly checks the input dimension (and this is the only difference between BatchNorm1D, 2D, and 3D). Therefore, **if one converts BNxD to SyncBN and then converts it back to BN, the input dimension check is no longer retained**. …

[Fix] Replace SyncBN with BN for inference

---

mmocr/utils/model.py
tests/test_utils/test_model.py

Such inconsistency could lead to the failure of inference with models which have SyncBN layers.

[Fix] fix inconsisent training/eval state after SyncBN->BN

---

mmocr/core/evaluation/hmean_ic13.py
mmocr/core/evaluation/utils.py
mmocr/datasets/pipelines/textdet_targets/base_textdet_targets.py
mmocr/datasets/pipelines/transforms.py
mmocr/models/textdet/postprocess/wrapper.py
requirements/build.txt
requirements/readthedocs.txt
requirements/runtime.txt
requirements/tests.txt
setup.cfg
tests/test_dataset/test_transforms.py
tests/test_metrics/test_eval_utils.py

Fixes #447
As reported in #447, our old IOU implementation using `Polygon3` has bugs in computing the intersection of two invalid polygons. `shapely.geometry.Polygon` is a better substitution that handles corner cases well.
I also found we were using `shapely.geometry.Polygon` and `Polygon3` together in this repo and they can be unified. `Polygon3` doesn't have clear documentation and will no longer be updated and distributed, with some chance to cause installation failure. (#385)
1. Refined the implementation of IOU, intersection and union utilities to handle corner cases
1. Migrated all the references to `Polygon3` to `shapely.geometry.Polygon`.
3. Supplemented some missed unit tests
No

[Fix] Add zero division handler in poly utils, remove Polygon3

---

mmocr/datasets/kie_dataset.py

Address https://github.com/open-mmlab/mmocr/issues/463
Here are the results from training a unet model with and without the modification. (training logs and epoch 60 checkpoints available on request)
Version|Best F1 score|F1 score @ 60 epochs
-|-|-
Old|0.894 @ epoch 43|0.884
New|0.895 @ epoch 44|0.888
The Wildreceipt dataset seems to have mostly axis-aligned polygons so we wouldn't have expected a noticeable different.

[Enhancement] Use bounding box around polygon instead of within polygon

---

configs/kie/sdmgr/sdmgr_unet16_60e_wildreceipt.py
mmocr/apis/inference.py
tools/test.py

Augmented mmdet's implementation of `single_gpu_test` with KIE-specific customization. Also fixed the assignment to the depreciated `pretrained` term in `init_detector`.

[Fix] Fix image export in test.py for KIE models

---

.github/workflows/build.yml

- Use containers in cuda checks which speeds up the CI process.
- Fix the disappearance of test coverage report

[Enhancement] Use container in CI

---

configs/textrecog/sar/metafile.yml

Original model `sar_r31_parallel_decoder_academic` weights path in sar/metafile.yml belongs to crnn which should be modified.

[Fix] Modify algorithm "sar" weights path in metafile

---

mmocr/apis/__init__.py
mmocr/apis/train.py
tools/train.py

The previous implementation did not always force all the processes to have the same random seed in DDP training, which may lead to inconsistent results across different runs. This PR fixes this issue by always broadcasting a random seed to all the processes during the training initialization phase.
https://github.com/open-mmlab/mmdetection/pull/6457

[Fix] Fix random seed

---

mmocr/apis/train.py

Transfer the processing steps of custom_hooks to MMCV.
None. MMCV 1.3.4 started to support this argument whereas MMOCR's minimum version requirement is 1.3.8.

[Enhancement] Pass custom_hooks to MMCV

---

.github/workflows/build.yml
.github/workflows/lint.yml

Related PR: https://github.com/open-mmlab/mmcv/pull/1533/

[Enhancement] Skip CI when some specific files were changed

---

docs/conf.py
docs_zh_CN/conf.py

This PR uses shared menu content from OpenMMLab's theme and removes duplicated contents from config, saving efforts on routine menu maintenance.

[Docs] Use shared menu from theme instead

---

README.md
README_zh-CN.md
docs/en/merge_docs.sh
docs/zh_cn/merge_docs.sh

1. Fixes dead links in readme
2. Append lines in-between when merging model readme files

[Docs] Docs fix

---

mmocr/utils/ocr.py

fix #665 
locals() dict should not be changed. [ref](https://docs.python.org/3/library/functions.html#locals)
If locals() runs more than once or during breakpoint debugging, the value of args will automatically become the dictionary before modification. 
In this case, a shallow copy is better.

[FIX] #665 fix change locals() dict

---

docs/en/dataset_types.md
mmocr/apis/__init__.py
mmocr/apis/inference.py
mmocr/apis/train.py
mmocr/apis/utils.py
mmocr/datasets/uniform_concat_dataset.py
tests/test_apis/test_model_inference.py
tests/test_apis/test_utils.py
tests/test_dataset/test_uniform_concat_dataset.py
tools/test.py

For example, It is useful when datasets are stored in different devices (hard-disk, aws-ceph). In that way, different `pipelines` should be applied to different datasets.

[Enhancement] Support muitiple pipelines for different datasets

---

requirements/runtime.txt

`cv2.connectedComponents` in OpenCV 4.5.5.62 has bugs that cause seg fault. We circumvent this problem by fixing the version of `opencv-python-headless` to be no greater than 4.5.4.60. This change is intended to be reverted when the bug gets fixed in OpenCV's latest release.
Related issue: https://github.com/opencv/opencv/issues/21366

[Fix] Fix opencv version to avoid some awared bugs

---

tools/train.py

The multi-threading feature of cv2 is incompatible with our multi-worker data preprocessing pipeline. As reported by https://github.com/open-mmlab/mmdetection/pull/6867:
> The CPU is too busy to handle the threads making the whole training speed is slow, and the system also get very lagging. The reason is that the cv2 module will activate multi-processing automatically and the processes number is equal to the CPU core. Which means if you have a more powerful CPU, it hurts the performance harder. My server has a 64-core CPU and 8 T4 GPU, if I set the workers_per_gpu to 4, the number of cv2-threads will be 8*4*64 = 2048. If I set the workers_per_gpu to 8, there will be 4096 theads. Each of this will overwhleming my system.
I tried out this patch on ABINet whose data loading process heavily …

[Enhancement] Disable multi-processing feature of cv2 to speed up data loading

---

tools/data/textdet/totaltext_converter.py
tools/data/textrecog/totaltext_converter.py

`yaml.load` has long been regarded as vulnerable and a certain type of loader has to be explicitly specified starting from `pyyaml==6.0`, which breaks our totaltext converters. Using `safe_load` to parse totaltext is just enough and officially recommended.
Fixes #751
`yaml.load` -> `yaml.safe_load` for both totaltext dataset converters.
None. `safe_load` is supported by older `pyyaml` as well.

[Fix] Use yaml.safe_load instead of load

---

configs/_base_/recog_pipelines/abinet_pipeline.py
configs/_base_/recog_pipelines/crnn_pipeline.py
configs/_base_/recog_pipelines/crnn_tps_pipeline.py
configs/_base_/recog_pipelines/nrtr_pipeline.py
configs/_base_/recog_pipelines/sar_pipeline.py
configs/_base_/recog_pipelines/satrn_pipeline.py
configs/_base_/recog_pipelines/seg_pipeline.py
configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py
configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt_openset.py

The configuration files didn't collect the necessary keys for test-time visualization and now it's fixed. Note that the pipelines of text detection models are not changed because the `Collect` transform will collect all necessary keys by default when `meta_keys` is not overridden.
For all test pipelines, I added necessary `meta_keys` to `Collect` for visualization.

[Fix] Add necessary keys to test_pipelines to enable test-time visualization

---

docker/Dockerfile

Implementation of suggested fix for #762 
Changing the installed version of mmdet in Dockerfile to 2.20.0
**Before PR**:
**After PR**:

fix #762: Bump mmdet version to 2.20.0 in Dockerfile

---

.github/workflows/build.yml
docs/en/install.md
docs/zh_cn/install.md

mmcv-full is only compiled on PyTorch 1.x.0 because the compatibility usually holds between 1.x.0 and 1.x.1. If your PyTorch version is 1.x.1, you can install mmcv-full compiled with PyTorch 1.x.0 and it usually works well.
https://github.com/open-mmlab/mmtracking/pull/409

update mmcv install

---

requirements/optional.txt

Legacy `albumentations` does not have some necessary features to support `Albu` pipeline wrapper from MMDetection. This PR requires users to use the newer one. Fixes #767
In legacy `albumentations`, the `Compose` method  does not accept `None` as `bbox_params` which is possible to happen in 
https://github.com/open-mmlab/mmdetection/blob/6ead4503a876971ed4d95d0cce9e9dc7ab8db31b/mmdet/datasets/pipelines/transforms.py#L1390-L1393

[Fix] Minimum version requirement of albumentations

---

demo/README.md
mmocr/utils/ocr.py
tests/test_utils/test_ocr.py

`mmocr/utils/ocr.py` always uses `cuda:0` as the default device even if the host does not have GPU. This PR changes this behavior and picks the best device when the user does not explicitly specify the device to run on.

[Enhancement] Automatically infer device for inference if not speicifed

---

tools/deployment/deploy_test.py
tools/deployment/onnx2tensorrt.py
tools/deployment/pytorch2onnx.py

Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in the future.
Add deprecation message in deployment tools.

Add deprecation message for deploy tools

---

README.md
README_zh-CN.md

- Add MMRotate repo URL.
- Group OpenMMLab projects based on their taxonomy, so that users could see related projects together.

Reorganizing OpenMMLab projects in readme

---

mmocr/utils/ocr.py
tests/test_utils/test_ocr.py

Fixes #796 
`mmocr.utils.ocr` can detect user's device but didn't wrap the result by `torch.device`. Therefore, the type of `MMOCR.device` is different case by case and can break some functions, such as `load_checkpoint`, that didn't manage to handle all possible input types.
Wrap the device result by `torch.device` and update unit tests accordingly.

[Fix] Standardize the type of torch.device in ocr.py

---

docs/en/training.md

The only way to use multiple GPUs for training is via `dist_train.sh`, whereas our docs can be misleading. Addresses #816

[Docs] Correct misleading section title in training.md

---

configs/_base_/recog_models/abinet.py
configs/textrecog/abinet/abinet_vision_only_academic.py

Without `num_classes=num_chars` specified in `ABILoss`, users who want to adapt the architecture to the dictionary size by changing `num_chars` only would encounter an error in loss computation.
Ref: #803

[Fix] Add num_classes to configs of ABINet

---

mmocr/models/textrecog/convertors/base.py
tests/test_models/test_label_convertor/test_attn_label_convertor.py
tests/test_models/test_label_convertor/test_base_label_convertor.py
tests/test_models/test_label_convertor/test_ctc_label_convertor.py

`BaseConvertor` used to skip any whitespace when loading a dictionary from a file. For example, one passes a legal dictionary file to `label_convertor` where the third line is a space character:
```
a
b
d
```
And they would expect the label convertor to create the dictionary as `['a', 'b', ' ', 'd']` but get `['a', 'b', 'd']` instead. This PR improves the parser by stripping only line-breaking characters (`\r` and `\n`) from each line and retaining the space character. 
1. Improve on the parsing part of …

[Fix] Support loading space character from dict file

---

mmocr/models/textrecog/losses/ce_loss.py
tools/data/utils/txt2lmdb.py

When caculating `CrossEntropy `loss in attention decoder, we can assign `ignore_index` to skip the loss of `<PAD>` token. In MMOCR, this assigning process is automatically done at [here](https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textrecog/recognizer/encode_decode_recognizer.py#L60)
```python
loss.update(ignore_index=self.label_convertor.padding_idx)
```
However, in [SARLoss](https://github.com/open-mmlab/mmocr/blob/main/mmocr/models/textrecog/losses/ce_loss.py#L67), the ignore index is initialized as `0` which may cause confusing, even if it won't work as we can automatically update the `ignore_index`. So we'd like to reset this value to `-1`.

[Fix] ignore_index in SARLoss

---

.circleci/config.yml

Due to the filtering rule, the main branch commits may run the PR stage Test after submitting a new Pull Request.
Now the filtering rule is updated by adding `<< pipeline.git.branch >>`, so the test can only be triggered by its own branches.
```yaml
filters:
branches:
only:
- /pull.*/
- << pipeline.git.branch >>
```

[Fix] Fix CircleCi Main Branch Accidentally Run PR Stage Test

---

mmocr/apis/train.py
tools/test.py

This PR enhances the configuration flexibility of `train_dataloader`, `val_dataloader` and `test_dataloader`. Users can customize more options in dataloaders rather than a subset of predefined fields. This PR also refines default dataloader configs.
https://github.com/open-mmlab/mmdetection/pull/7668

[Enhancement] More customizable fields in dataloaders

---

configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py
mmocr/core/evaluation/hmean.py
mmocr/datasets/icdar_dataset.py
mmocr/datasets/text_det_dataset.py
tests/test_dataset/test_icdar_dataset.py

The current implementation of `eval_hmean` only provides a parameter to set the minimum score with which the boundaries are used for evaluation. However, it always evaluates the filtered boundaries on a fixed set of threshold values `[0.3, 0,4, ..., 0.9]` no matter what the minimum score is, which is an inflexible and illogical design. There is also no entry in the config to customize such a behavior.
This PR replaces `score_thr` with `min_score_thr, max_score_thr, step` so that users can configure the search space via input parameters. `IcdarDataset.evaluate()` is modified to allow these three parameters to be customized through the config file. 
For example, by adapting the following snippet in the config, one can evaluate the model's output on a list of boundary score thresholds `[0.1, …

[Enhancement] Support dynamic threshold range in eval_hmean

---

requirements/runtime.txt

OpenCV has released 4.5.5.64, and this PR is intended to check if the issue in #694 still persists. Since `opencv-python-headless` does not have visualization utils which led to many issues from the community, this PR replaces this library with the full one to avoid any further confusion.
Update: 4.5.5.64 still not have it fixed yet.

[Enhancement] Replace `opencv-python-headless` with `open-python`

---

mmocr/datasets/icdar_dataset.py
mmocr/datasets/uniform_concat_dataset.py
tests/test_dataset/test_uniform_concat_dataset.py

Since text recognition models are usually evaluated on multiple datasets, it's hard to compare the model's performance across epochs without a unified indicator such as the mean scores. This PR supports `get_mean` in `UniformConcatDataset`. When it's on, the mean score of `{metric_name}` across concatenated datasets will be added to the evaluation results with the name `mean_{metric_name}`.
Modified `mmdet.datasets.ConcatDataset.evaluate()` to compute the mean scores when both `self.separate_eval` and `self.get_mean` are True. Also disabled evaluating the datasets as a whole as this feature was not verified on MMOCR. We don't want to make excessive changes in this PR.
No

[Feature] Support computing mean scores in UniformConcatDataset

---

mmocr/datasets/uniform_concat_dataset.py
tests/test_dataset/test_uniform_concat_dataset.py

Since `show_mean_scores` was a bit unintuitive to find and set, this PR changes its default value to 'auto' to let the program automatically report mean scores when there is more than 1 dataset to evaluate.

[Enhancement] Automatically report mean scores when applicable

---

mmocr/core/evaluation/ocr_metric.py
mmocr/datasets/ocr_dataset.py
tests/test_dataset/test_ocr_dataset.py

Though MMOCR provides 6 evaluation metrics for text recognition tasks, there was no way to configure the metric(s) to evaluate the model, which usually results in an unnecessarily ong performance report. This PR enables the configuration entrance and users now can evaluate models on a subset of metrics selectively.
Take the evaluation config in `configs/textrecog/crnn/crnn_academic_dataset.py` as an example. 
```python
evaluation = dict(interval=1, metric='acc')
```
The recognition metric `acc` is short for a collection of 6 metrics. One can expect a full performance report at the end of an evaluation cycle:
```python
{'0_char_recall': 0.0484, '0_char_precision': 0.6, '0_word_acc': 0.0, '0_word_acc_ignore_case': 0.0, '0_word_acc_ignore_case_symbol': 0.0, '0_1-N.E.D': 0.0525}
```
After …

[Enhancement] Allow choosing metrics to report in text recognition tasks

---

.circleci/config.yml
.circleci/test.yml

According to the current config, full tests are triggered when CircleCI does not detect the changes in a set of paths. However, it was logically wrong since if a commit changes both the docs and code, `lint_only` will still be true and no full tests would be performed. This PR flips the mapping around to ensure no undesired skips when the case above happens.

[Fix] Fix lint_only in CircleCI

---

docs/en/datasets/det.md
docs/en/datasets/recog.md
tools/data/textdet/art_converter.py
tools/data/textrecog/art_converter.py

ArT is a widely-used arbitrary scene text dataset that already contains Total-text and Ctw-1500, and extra curved scene text. Also, it refines the annotations of CTW-1500, and all Chinese texts are annotated in line-level while English samples are word-level.
add `art_converter.py` for textdet and textrecog
See doc

[Feature] Add ArT

---

.github/workflows/test_mim.yml

Ref: https://github.com/open-mmlab/mmsegmentation/pull/1654

[Enhancement] Test mim in CI

---

tools/data/textdet/lv_converter.py

Address issue https://github.com/open-mmlab/mmocr/issues/1078
If this PR introduces a new feature, it is better to list …

Flexible ways of getting file name

---

mmocr/models/kie/heads/sdmgr_head.py

While understanding the SDMG-R model for Key Information Extraction, the forward pass seemed to be updating the edge embedding in the last layer of GNN. The item was discussed with the author https://github.com/open-mmlab/mmocr/issues/1122 to confirm and its fix
For the KIE model, the edge embedding were not getting updated after every GNN layer in the model forward pass.
**Before PR**:
**After PR**:

Updating edge-embeddings after each GNN layer

---

tools/train.py

cfg.get is better way to access the params when it may not exist.
According to #1140, I fix the config parameter access method.
`cfg.checkpoint_config` raises error when it doesn't exist. `cfg.get("checkpoint_config", None)` is better. It's a least modification and won't affect other codes.
NA
NA
**Before PR**:
**After PR**:

bug fix: access params by cfg.get

---

docs/en/tools.md
mmocr/utils/lmdb_util.py
tools/data/utils/lmdb_converter.py

Misleading default value of --lmdb-map-size. #1142 
109951162776 may refer to 1TB（1099511627776 in fact）, digit 7 left.
Change default value from 109951162776 to 1099511627776 and add doc.

fix typo of --lmdb-map-size default value

---

requirements/docs.txt

Otherwise the documentation can not be built.
https://github.com/open-mmlab/mmcv/pull/2121

[Docs] Limit markdown version

---

docs/en/datasets/recog.md

Update lmdb_converter and ct80 cropped data source
1. `tools/data/utils/txt2lmdb.py` is replaced with `lmdb_converter.py` but didn't update in the document (resolve #1088)
2. ct80 labels are for cropped images while didn't provide the cropped data source in the document (resolve #536).
1. replace `txt2lmdb.py` with `lmdb_converter.py` with the correct usage.
2. update the data preparation for ct80, data source from [gaotongxiao's answer](https://github.com/open-mmlab/mmocr/issues/536#issuecomment-950658357)
**Before PR**:
**After PR**:

[Fix] Update lmdb_converter and ct80 cropped image source in document

---

mmocr/models/textrecog/backbones/mobilenet_v2.py

It was missed to add `init_cfg` in mobilenet backbone, which caused an error at inference.

[Fix] Fix mobilenet init

---

README.md
README_zh-CN.md

Hello open-mmlab and mmocr team !
Thank you for your work on MMOCR.  This project is interesting, and we think that it would be a great addition to make this great work instantly discoverable & available as an API for all your users, to quickly try and use it in their applications.
On Tiyaro, every model in MMOCR will get it’s own:
- Dedicated model card - Example: [open-mmlab/mmocr/crnn_tps](https://console.tiyaro.ai/explore/mmocr-CRNN_TPS_recog/api)
- Model demo - Example: [open-mmlab/mmocr/crnn_tps](https://console.tiyaro.ai/explore/mmocr-CRNN_TPS_recog/demo)
- Unique Inference API - Example: [open-mmlab/mmocr/crnn_tps](https://api.tiyaro.ai/v1/ent/open-mmlab/1.0/mmocr/CRNN_TPS_recog)
- Sample code snippets and swagger spec for the API
Users will also be able to compare your model with …

docs: demo, experiments and live inference API on Tiyaro

---

mmocr/datasets/recog_lmdb_dataset.py

This PR fixes：
1. `super().__init__()` will concat `self.ann_file` and `self.data_root`, however, the first `_get_env()` will be called before `super().__init__()`, hence, the `ann_file` cannot be found if it is not an absolute path. And this issue cannot be solved by simply move the `super().__init__()` to the beginning of `init()`, because the `super().__init()__` relies on `self.total_number` which is obtained by `_get_env()`. Therefore, this PR adds a `root` arg to help the `_get_env()` to get the correct path in `init()`.

[Fix] Fix LMDB dataset

---

docs/zh_cn/user_guides/inference.md
mmocr/datasets/transforms/wrappers.py

Fixes https://github.com/open-mmlab/mmocr/issues/1426
Sometimes ImgAug could produce some invalid polygons after applying augmentations to a polygon set and may interfere with the training process. This PR checks and skips every invalid polygon and can alleviate this issue.

[Fix] Skip invalud augmented polygons in ImgAugWrapper

---

mmocr/models/textdet/postprocess/pse_postprocessor.py

When I follow the documentation to convert the psenet model to torchserve model and start the torchserve service, the predicted image will receive a 503 error. The reason is that the float32 type of numpy will throw an exception during serialization, and the confidence type in the result predicted by pse is numpy.float32
Convert the confidence type in the PSE post-processing file from numpy.float32 to python built-in float

Convert numpy.float32 type to python built-in float type

---

tools/analysis_tools/offline_eval.py

Fixed https://github.com/open-mmlab/mmocr/issues/1496
The new OpenMMLab convention now requires every test-time DataSample output to contain both ground truth and prediction information. MMEngine has changed its `offline_evaluate` interface accordingly but MMOCR's offline_eval.py hasn't.

[Fix] Fix offline_eval error caused by new data flow

---

mmocr/models/common/backbones/__init__.py
mmocr/models/common/backbones/clip_resnet.py
mmocr/models/common/plugins/__init__.py
mmocr/models/common/plugins/common.py
tests/test_models/test_common/test_backbones/test_clip_resnet.py
tests/test_models/test_common/test_plugins/test_avgpool.py

To support modified resnet structure used in [oCLIP](https://github.com/bytedance/oclip), which is also the official structure in [CLIP](https://github.com/openai/CLIP).
Currently, I only implement CLIPResNet-50 when depth=50. CLIPResNet-101 would be implemented later.
We also provide a [script](https://github.com/bytedance/oclip/blob/main/tools/convert2mmocr.py) for converting the parameter names of our models to MMOCR style.
For more information, please refer to [oCLIP](https://github.com/bytedance/oclip)
Add a new ResNet structure, named as CLIPResNet in mmocr/models/common/backbones/clip_resnet.py
**Before PR**:
**After PR**:

[Feature] support modified resnet structure used in oCLIP

---

mmocr/datasets/preparers/data_converter.py
mmocr/datasets/preparers/dumpers/dumpers.py

1. a redundant blank in automatically generated dataset config
2. when using `TextRecogCropConverter`, the packed sample list contains multiple instances, which should be flattened:
```{json}
//  before fix bug2
data_list = [
[dict(), dict(), dict()], [dict()], [dict()]
]
// after fix bug2
data_list = [
dict(),
dict(),
dict(),
dict(),
dict()
]
```

[Fix] Fix two bugs in dataset preparer

---

mmocr/datasets/preparers/data_obtainer.py

When re-running the data preparer, it might repeatedly download the annotation files.

[Fix] Fix Dataset Preparer Extract

---

dataset_zoo/cute80/metafile.yml
dataset_zoo/cute80/sample_anno.md
dataset_zoo/cute80/textrecog.py

This PR relies on the updated `ICDARTxtTextRecogAnnParser` in #1529

[Featuare] Add cute80 to dataset preparer

---

docs/en/dataset_zoo.py
docs/zh_cn/dataset_zoo.py

When the dataset name in metafile contains symbols such as '(' and ')', the script failed to generate a link to dataset details.

[Fix] Fix Dataset Zoo Script

---

mmocr/datasets/preparers/data_converter.py

Delete category in rec json
```python
"metainfo": {
"dataset_type": "TextRecogDataset",
"task_name": "textrecog",
"category": [
{
"id": 0,
"name": "text"
}
]
}
```
`TextRecogCropConverter` defaults not to padding in `crop image`

[Bugs] fix crop without padding and recog metainfo delete unuse info

---

dataset_zoo/icdar2013/metafile.yml
dataset_zoo/icdar2013/sample_anno.md
dataset_zoo/icdar2013/textdet.py
dataset_zoo/icdar2013/textrecog.py
dataset_zoo/icdar2013/textspotting.py

[Feature] Add IC13 preparer

---

mmocr/apis/inferencers/mmocr_inferencer.py

bash
```bash
python3 -m mmocr.ocr \
--det DB_r18 \
--recog CRNN \
demo/demo_text_ocr.jpg \
--pred-out-file temp/demo_text_ocr.pkl
```
output
```
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/root/dev/oss/src_mmocr/mmocr/ocr.py", line 487, in <module>
main()
File "/root/dev/oss/src_mmocr/mmocr/ocr.py", line 483, in main …
```

[Fix] Change mmcv.dump to mmengine.dump

---

dataset_zoo/cute80/textrecog.py

Based on https://github.com/open-mmlab/mmocr/pull/1552

[Dataset] Update CT80 config

---

dataset_zoo/icdar2013/textrecog.py

Updated the provided annotations so that the image paths should be correct now.

[Fix] Fix IC13 textrecog annotations

---

configs/textrecog/crnn/crnn_mini-vgg_5e_toy.py
mmocr/models/textrecog/module_losses/ctc_module_loss.py

When the target is empty, the `target_length` is not equal to the actual `target_length` for
`target_lengths = torch.clamp(target_lengths, max=seq_len).long()` 
The precision of toy data in CRNN can be 100%

[Bugs] ctc loss bug if target is empty

---

mmocr/datasets/icdar_dataset.py
tests/test_datasets/test_icdar_dataset.py

refer to https://github.com/open-mmlab/mmdetection/pull/9469

[Refactor] Refactor icdardataset metainfo to lowercase.

---

docs/en/user_guides/dataset_prepare.md
docs/en/user_guides/useful_tools.md
docs/zh_cn/user_guides/dataset_prepare.md
docs/zh_cn/user_guides/useful_tools.md
mmocr/visualization/kie_visualizer.py
mmocr/visualization/textdet_visualizer.py
mmocr/visualization/textrecog_visualizer.py
mmocr/visualization/textspotting_visualizer.py
tools/analysis_tools/browse_dataset.py

Now browse_dataset.py supports two modes, `model config mode` and `dataset config mode`. Users can input dataset config now, and the script will automatically select the corresponding mode.

[Feature] Support browse_dataset.py to visualize original dataset

---

mmocr/models/textdet/module_losses/db_module_loss.py

训练自定义数据集时遇到RuntimeWarning如下
调试定位到出错原因如下：
由于pt1, pt2都是float32，计算a_square, b_square, c_square存在数值精度问题
导致后续根据余弦公式计算neg_cos_c时出现了小于-1或者大于1的情况
从而使得计算distance时sqrt下a_square * b_square * square_sin 出现负数
https://github.com/open-mmlab/mmocr/blob/24bfb1876808807e2cb595b31aea2ae9819e2ec0/mmocr/models/textdet/module_losses/db_module_loss.py#L278-L294
解决方法：
将计算得到的neg_cos_c值进一步限制在[-1,1]间
If so, please describe how it breaks the …

[Fix] db_module_loss，negative number encountered in sqrt

---

mmocr/datasets/transforms/__init__.py
mmocr/datasets/transforms/ocr_transforms.py
mmocr/datasets/transforms/textdet_transforms.py
mmocr/datasets/transforms/wrappers.py
mmocr/utils/__init__.py
mmocr/utils/polygon_utils.py
mmocr/utils/transform_utils.py
tests/test_datasets/test_transforms/test_adapters.py
tests/test_datasets/test_transforms/test_ocr_transforms.py
tests/test_datasets/test_transforms/test_textdet_transforms.py
tests/test_datasets/test_transforms/test_wrappers.py
tests/test_utils/test_polygon_utils.py
tests/test_utils/test_transform_utils.py

Based on #1623.
1. There are a few more possible cases for invalid polygons which should be addressed in `FixInvalidPolygon`.
2. Some third-party augmentation libraries, such as ImgAug, may produce polygons not regarded as valid by `shapley`.
3. Sometimes there is a need to remove ignored instances from the pipeline. 
1. Enhance `FixInvalidPolygon` by tacking some corner cases which are usually seen in some datasets, and move it to `ocr_transforms.py` since it's general enough now.
2. Let `ImgAugWrapper` invokes `FixInvalidPolygon` to deal with some weird shape polygons by default.
3. Add `RemoveIgnored` transform to `ocr_transforms.py` as well.
4. Add `transform_utils.py` and implement `remove_pipeline_elements`.

[Enhancement] Enhance FixInvalidPolygon, add RemoveIgnored transform

---

docs/zh_cn/user_guides/useful_tools.md

[Docs] Add Chinese translation for browse_dataset.py

---

mmocr/models/textdet/necks/fpem_ffm.py
mmocr/utils/__init__.py
tests/test_models/test_textdet/test_necks/test_fpem_ffm.py
tests/test_utils/test_bbox_utils.py
tests/test_utils/test_check_argument.py

[UT] Add missing unit tests

---

mmocr/utils/polygon_utils.py

Addressing https://github.com/open-mmlab/mmocr/issues/1688
numpy has deprecated the usage of using `np.array` to create a ragged sequence without `dtype=object`.

[Fix] Explicitly create np object array for compatibility

---

docs/en/get_started/install.md
docs/zh_cn/get_started/install.md
mmocr/__init__.py

Merge after https://github.com/open-mmlab/mmocr/pull/1608
ABCNet relies on `BezierAlign` in MMCV 2.0.0rc4, and the new inferencers rely on `BaseInferencer` in MMEngine 0.5.0.

[Enhancement] Revise upstream version limit

---

mmocr/utils/polygon_utils.py

`shapely` raises a warning when users try to get the intersection of two non-overlapping polygons, resulting in overwhelming warnings in the first few training iterations when the text detection model cannot generate correct predictions and the metric tries to compute IoU between them and gts.
Close #1674

[Fix] Detect intersection before using shapley.intersection to eliminate spurious warnings

---

mmocr/datasets/preparers/parsers/coco_parser.py

The ignore flag of textocr was always set to `False`. However, this dataset indeed uses `'.'` to represent illegible or non-English texts.

[Fix] Fix textocr ignore flag

---

tools/model_converters/publish_model.py

https://github.com/open-mmlab/mmdetection/pull/9356
The checkpoint saved by mmengine contains more keys (e.g. message_hub, param_scheduler). These parts are very large and may take dozens or even hundreds of MB.
Pop the keys except for meta and state_dict.

[Enchancement] Only keep meta and state_dict when publish model

---

docs/en/api/datasets.rst
docs/zh_cn/api/datasets.rst
mmocr/datasets/samplers/__init__.py
mmocr/datasets/samplers/batch_aug.py
tests/test_datasets/test_samplers/test_batch_aug.py

[Batch augmentation](https://openaccess.thecvf.com/content_CVPR_2020/papers/Hoffer_Augment_Your_Batch_Improving_Generalization_Through_Instance_Repetition_CVPR_2020_paper.pdf) is a trick that improves the model's generalization ability. It's done by repeating the same data instance for several times and let each of them goes through parallel data augmentations in a single batch.
In MMOCR, the same effect can be achieved by using `BatchAugSampler`, which generates the same index for `num_repeat` times consecutively. And the final "dataset length" will be `num_repeat` times the original dataset length. 
That is, a dataset comprising of `[0, 1, 2, 3]` may be randomly shuffled and sampled by `BatchAugSampler` and what dataloader finally gets could be `[2, 2, 1, 1, 0, 0, 3, 3]` when …

[Feature] Support batch augmentation through BatchAugSampler

---

dataset_zoo/icdar2015/textrecog.py
docs/en/user_guides/data_prepare/dataset_preparer.md
docs/zh_cn/user_guides/data_prepare/dataset_preparer.md
mmocr/datasets/preparers/config_generators/base.py
mmocr/datasets/preparers/config_generators/textrecog_config_generator.py
mmocr/datasets/preparers/data_preparer.py
mmocr/datasets/preparers/dumpers/__init__.py
mmocr/datasets/preparers/dumpers/lmdb_dumper.py
mmocr/datasets/preparers/obtainers/naive_data_obtainer.py
tools/dataset_converters/prepare_dataset.py

[Feature] Support lmdb format in Dataset Preparer

---

mmocr/models/textdet/heads/drrg_head.py
mmocr/models/textdet/module_losses/drrg_module_loss.py
requirements/readthedocs.txt
requirements/runtime.txt
requirements/tests.txt

`lanms-neo` has long been complained to block the installation on some edge devices, but it is only required by `DRRG` as of now and removing it from requirements does not seem to make a significant impact in the future.

[Enhancement] Make lanms-neo optional

---

docs/en/user_guides/inference.md
docs/zh_cn/user_guides/inference.md
mmocr/apis/inferencers/mmocr_inferencer.py

in response to #1799
The **MMOCRInferencer.\_\_call__** method is modified to provide the flexibility of setting different values for **det_batch_size**, **rec_batch_size**, **kie_batch_size**, and **chunk_size**. Any one of these 4 parameters will override **batch_size** if it is not **None**.
To maintain backward compatibility, the default behavior of **MMOCRInferencer.\_\_call__** will remain unchanged.
**Before PR**:
**After PR**:

decouple batch_size to det_batch_size, rec_batch_size and kie_batch_size in MMOCRInferencer

---

configs/textrecog/abinet/_base_abinet-vision.py

In response to #1794
change blur_limit config of Albumentation MotionBlur form 6 to 7 to fix `ValueError: Blur limit must be odd when centered=True. Got: (3, 6)`
**Before PR**:
**After PR**:

Abinet: fix ValueError: Blur limit must be odd when centered=True. Got: (3, 6)

---

mmocr/visualization/kie_visualizer.py

```shell
root@023ca4a78cff:/mmocr# CUDA_VISIBLE_DEVICES=2,3,4 python tools/infer.py demo/0000ae6cbdb1.png --det DBNet --rec CRNN --kie configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt-openset.py --kie-weights /home/making-graphs-accessible/input/epoch_2.pth --show --print-result
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmocr/textdet/dbnet/dbnet_resnet50-oclip_1200e_icdar2015/dbnet_resnet50-oclip_1200e_icdar2015_20221102_115917-bde8c87a.pth
04/03 03:06:10 - mmengine - WARNING - "FileClient" will …
```

[Bug] Bug generated during kie inference visualization

---

mmocr/models/textdet/postprocessors/pse_postprocessor.py

Fix the bug only :>
Correct the logic of min text area. The old version of code will let the model of PseNet predict really small text box region.
I just change the operator "or" to "and" for the correctness of the logic. 
If so, please describe how it breaks the …

Fix the logic of min text area in PostProcess of PseNet

---

tools/test.py

To improve the test tool, when testing model with tools/test.py and "--save-preds" option. 
When the `test_evaluator` config is a dict and `--save-preds` is in `tools/test.py`'s option, the runner cannot correctly buid the evaluator.For example:
My config file
```python
test_evaluator = dict(
type='MultiDatasetsEvaluator',
metrics=[
dict(
type='WordMetric',
mode=['exact', 'ignore_case', 'ignore_case_symbol']),
dict(type='CharMetric')
],
dataset_prefixes=None)
```
My test script
```console
python tools/test.py \
work_dirs/master_resnet31_12e.py \
work_dirs/best_ocr_rec_1_recog_char_f1_epoch_980.pth \
--save-preds
```
the `--save-preds` option will concat the evaluator with a `DumpResults` instance in a wrong way,the new evaluator is like:
```python
test_evaluator = [ …
```

When testing my model with tools/test.py, my config will be messed up by the "--save-preds" option. 
