requirements/docs.txt, requirements/readthedocs.txt
=> Fix readthedocs

.github/workflows/build.yml, setup.py
=> Revert "Enable gpu ci"

README_zh-CN.md
Added space between chinese and english characters.
=> fix pr#70 based on ZZL's comments

README.md
added chinese readme.md link to english readme
=> added link to readme.md

mmocr/datasets/pipelines/textdet_targets/textsnake_targets.py
=> fix #101: fix assertion

docker/Dockerfile
=> Add libGL1-mesa-glx to Dockerfile

mmocr/datasets/pipelines/ocr_transforms.py
=> added img_norm_cfg key-value pair for toy data visualization

configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py
add img_norm_cfg to meta_keys in sar toy config
=> add img_norm_cfg to config

configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py
added ori_filename to save prediction to show_dir
=> Visualise toy

mmocr/datasets/pipelines/textdet_targets/textsnake_targets.py, mmocr/datasets/pipelines/transforms.py, tests/test_dataset/test_textdet_targets.py, tests/test_dataset/test_transforms.py, tests/test_models/test_detector.py
Fix #122: adapt textsnake targets to other datasets
=> Fix issue 122

demo/image_demo.py
- Changed save_path to out_file.
- Returned original image when prediction is none.
=> fix issue#127: changed save_path to out_file

mmocr/datasets/kie_dataset.py, mmocr/datasets/pipelines/__init__.py, mmocr/datasets/pipelines/box_utils.py
=> Add sort_vertex8 helper function

mmocr/models/textdet/detectors/text_detector_mixin.py
Now show bounding box when output_file is specified
=> show bounding box in img_demo output

mmocr/datasets/kie_dataset.py, mmocr/datasets/utils/loader.py
- Use `mmcv.list_from_file` instead of manually parsing text lines
- Use array.T for transpose
=> Improve some writings

mmocr/datasets/kie_dataset.py, mmocr/datasets/pipelines/kie_transforms.py, tests/test_dataset/test_kie_dataset.py
* allow data do not contain label
* Make relation float32
=> Improve KIE

tests/test_dataset/test_dbnet_transforms.py
fix #58 
- Add dbnet transformation unit tests
=> Unit tests of dbnet transform

mmocr/models/textrecog/losses/ce_loss.py, mmocr/models/textrecog/losses/ctc_loss.py, mmocr/models/textrecog/recognizer/encode_decode_recognizer.py
Fix ctc_loss NaN bug by setting `zero_infinity=True, flatten=False` for ctc_loss
=> fix bug of loss nan

setup.py
add include_package_data to setup.py
=> add include_package_data to setup.py

requirements/mminstall.txt
add mminstall.txt which includes mmcv-full 1.3.1 and mmdet 2.11.0
=> add mminstall.txt

configs/kie/sdmgr/metafile.yml, configs/textdet/dbnet/metafile.yml, configs/textdet/maskrcnn/metafile.yml, configs/textdet/panet/metafile.yml, configs/textdet/psenet/metafile.yml, configs/textdet/textsnake/metafile.yml, configs/textrecog/crnn/metafile.yml, configs/textrecog/nrtr/metafile.yml, configs/textrecog/robust_scanner/metafile.yml, configs/textrecog/sar/metafile.yml, configs/textrecog/seg/metafile.yml, configs/textrecog/tps/metafile.yml, model_zoo.yml
=> Add metafiles

MANIFEST.in
=> add manifest.in

tools/kie_test_imgs.py, tools/ocr_test_imgs.py, tools/publish_model.py, tools/test.py, tools/test_imgs.py, tools/train.py
By adding shebang to file header and adding `+x`.
=> Make tools executable

tests/test_models/test_detector.py
=> Test more on cpu

tools/kie_test_imgs.py
Fix https://github.com/open-mmlab/mmocr/issues/88
=> Support cpu in kie visualization

demo/ocr_image_demo.py
To verify, use
```bash
python demo/ocr_image_demo.py demo/demo_text_det.jpg demo/output.jpg --device cpu --det-config configs/textdet/textsnake/textsnake_r50_fpn_unet_1200e_ctw1500.py --det-ckpt https://download.openmmlab.com/mmocr/textdet/textsnake/textsnake_r50_fpn_unet_1200e_ctw1500-27f65b64.pth
```
=> Support cpu for ocr demo

mmocr/datasets/pipelines/box_utils.py, tests/test_dataset/test_crop.py
=> Speed up sort_vertex

.gitignore, mmocr/datasets/kie_dataset.py, mmocr/models/kie/losses/sdmgr_loss.py
Move f1 computation to cpu to fit the distributed scenario
=> Support distributed evaluation of KIE

README.md, README_zh-CN.md
Hi, found a small link typo error, not sure if it is on purpose.
=> Fix readme crnn link

mmocr/models/textdet/necks/fpn_cat.py
Hi, this PR tries to fix dbnet dynamic input error. For some users may use dynamic input, we may concern interpolating tensors with desired shape other than scale_factor.
THX.
=> Fix dbnet dynamic input

docs/datasets.md, tools/data/textrecog/totaltext_converter.py
added totaltext converter to generate cropped images and ann .txt file
=> added totaltext recog converter

tests/test_core/test_deploy_utils.py
=> fix unit tests

demo/ocr_image_demo.py
=> [Fix] fix wrong import path

docs/datasets.md, tools/data/textdet/textocr_converter.py, tools/data/textrecog/textocr_converter.py
TODO: benchmark DBNet and CRNN
=> add TextOCR dataset converter

configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py, mmocr/datasets/kie_dataset.py, tests/test_dataset/test_kie_dataset.py, tools/kie_test_imgs.py
Fixed by loading img by hand if no img was there
I will add a test for this script later.
=> Fix kie_test_imgs script for novisual

mmocr/core/deployment/deploy_utils.py, tests/test_core/test_deploy_utils.py, tests/test_models/test_detector.py, tests/test_models/test_recognizer.py, tools/deployment/onnx2tensorrt.py
Hi, this is a PR for fixing #291 .
Remove temporary files generated during unit tests.
=> [Fix] Fix unit tests, remove temporary files 

mmocr/models/textdet/losses/fce_loss.py
=> fcenet fix bug

configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py, configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
The extra comma in the config files make the annotation file invalid
=> [Fix] fix nrtr config

tools/data/textrecog/synthtext_converter.py
Added integer casting to avoid potential breaking
=> fix syntext_converter

docs_zh_CN/datasets.md
Add CN version of `datasets` document.
=> fix #347: add docs_zh_CN/datasets.md

.gitignore, MANIFEST.in, README.md, README_zh-CN.md, setup.py
1. Update setup.py to link or copy files required by mim into mmocr/.mim
2. Add intro to MIM in README
=> [Feature] Support MIM

tools/data/textrecog/totaltext_converter.py
=> [Fix] Totaltext_converter: skip invalid annotations

requirements/readthedocs.txt, requirements/runtime.txt
Fixes #230 based on the suggestion from @gen-ko
=> [Fix] replace lanms-proper with lanms-neo

mmocr/apis/train.py, tools/test.py
Before this pr, it was ignored.
=> Support persistent_workers option in data loader

.github/workflows/build.yml, setup.py
...and remove CI for PyTorch 1.5 in sync with docs.
=> [Enhancement] Add py3.9 CI

model-index.yml
Add some missing configs back to model-index
=> [Enhancement] update model-index.yml

configs/kie/sdmgr/metafile.yml, configs/textdet/dbnet/metafile.yml, configs/textdet/drrg/metafile.yml, configs/textdet/fcenet/metafile.yml, configs/textdet/maskrcnn/metafile.yml, configs/textdet/panet/metafile.yml, configs/textdet/psenet/metafile.yml, configs/textdet/textsnake/metafile.yml, configs/textrecog/crnn/metafile.yml, configs/textrecog/nrtr/metafile.yml, configs/textrecog/robust_scanner/metafile.yml, configs/textrecog/sar/metafile.yml, configs/textrecog/satrn/metafile.yml, configs/textrecog/tps/metafile.yml
Add "title" to paper as requested by upstream
=> [Fix] fix paper field in metafiles

configs/textrecog/crnn/metafile.yml, configs/textrecog/nrtr/metafile.yml, configs/textrecog/robust_scanner/metafile.yml, configs/textrecog/sar/metafile.yml, configs/textrecog/satrn/metafile.yml, configs/textrecog/seg/metafile.yml, configs/textrecog/tps/metafile.yml
=> [Fix] Unify recognition task names in metafiles

mmocr/apis/inference.py
See https://github.com/open-mmlab/mmdetection/pull/6405
=> [Fix] Always map location to cpu when loading checkpoint

mmocr/models/textdet/dense_heads/head_mixin.py, tests/test_models/test_detector.py
=> [Feature] Save filename in text detection test results

configs/kie/sdmgr/README.md, docs/datasets/kie.md, docs/index.rst, docs/tutorials/kie_closeset_openset.md, docs_zh_CN/datasets/kie.md, docs_zh_CN/index.rst, docs_zh_CN/tutorials/kie_closeset_openset.md
=> [Docs] Docs for KIE CloseSet & OpenSet

tools/recog_test_imgs.py
=> [Fix] Fix wrong model builder in recog_test_imgs

docs/getting_started.md, docs_zh_CN/getting_started.md
=> [Docs] Fix broken links

demo/README.md, mmocr/utils/ocr.py
1. Fix #524 
2. Supplement descriptions to docs
=> [Feature] Add SAR_CN to ocr.py

docs/deployment.md
C++ inference example with opencv and onnxruntime.
=> C++ example section

.circleci/config.yml, tests/test_utils/test_ocr.py
Initiating CircleCI for real statistics.
1. Add config for CircleCI
2. Allow minor floating errors when testing ocr.py
=> [Enhancement] CircleCI Setup

tools/train.py
Removing it as MMCV can handle this field.
=> [Enhancement] Remove unnecessary custom_import from train.py

configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py
Fix the config of DB_r50 so that its test result matches that of claimed in the docs.
=> [Fix] Fix DBNet_r50 config

configs/kie/sdmgr/README.md, configs/ner/bert_softmax/README.md, configs/textdet/dbnet/README.md, configs/textdet/drrg/README.md, configs/textdet/fcenet/README.md, configs/textdet/maskrcnn/README.md, configs/textdet/panet/README.md, configs/textdet/psenet/README.md, configs/textdet/textsnake/README.md, configs/textrecog/crnn/README.md, configs/textrecog/nrtr/README.md, configs/textrecog/robust_scanner/README.md, configs/textrecog/sar/README.md, configs/textrecog/satrn/README.md, configs/textrecog/seg/README.md, configs/textrecog/tps/README.md, docs/stats.py, docs_zh_CN/stats.py
Added abstract and image to readme files according to the new protocol. `stats.py` is also updated accordingly.
=> [Docs] Update model readme

docs/merge_docs.sh, docs_zh_CN/merge_docs.sh, mmocr/datasets/pipelines/__init__.py, mmocr/models/textdet/dense_heads/db_head.py, mmocr/models/textdet/dense_heads/drrg_head.py, mmocr/models/textdet/dense_heads/fce_head.py, mmocr/models/textdet/dense_heads/head_mixin.py, mmocr/models/textdet/dense_heads/pan_head.py, mmocr/models/textdet/dense_heads/pse_head.py, mmocr/models/textdet/dense_heads/textsnake_head.py, mmocr/models/textdet/losses/db_loss.py, mmocr/models/textdet/losses/drrg_loss.py, mmocr/models/textdet/losses/fce_loss.py, mmocr/models/textdet/losses/pan_loss.py, mmocr/models/textdet/losses/pse_loss.py, mmocr/models/textdet/losses/textsnake_loss.py, mmocr/models/textdet/necks/fpem_ffm.py, mmocr/models/textdet/necks/fpn_cat.py, mmocr/models/textdet/necks/fpn_unet.py, mmocr/models/textdet/necks/fpnf.py
1. Make merge_docs.sh to be local-building-friendly
2. Supplement docstrings for text detection models
=> [Docs] Docstring for textdet models

mmocr/apis/inference.py, mmocr/core/visualize.py, mmocr/utils/ocr.py
Fix https://github.com/open-mmlab/mmocr/issues/599
Verify:
```bash
./mmocr/utils/ocr.py --config-dir configs --det PS_CTW --recog SAR --kie SDMGR --print-result --output . --kie-config configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py --kie-ckpt https://download.openmmlab.com/mmocr/kie/sdmgr/sdmgr_novisual_60e_wildreceipt_20210517-a44850da.pth  demo/demo_kie.jpeg
```
=> Fix kie demo

setup.py
Related PR: https://github.com/open-mmlab/mmflow/pull/37/
=> [Feature] mim extension for windows

tools/data/textdet/totaltext_converter.py
Follow up PR of #375, fixes #659
=> [Fix] Remove depreciated image validator in totaltext converter

mmocr/core/deployment/deploy_utils.py, tools/deployment/deploy_test.py
=> fix sartrn onnxruntime test

mmocr/models/textrecog/decoders/sar_decoder.py
=> fix a bug for sar decoder when bi-rnn is used

.pre-commit-config.yaml
Related PR: https://github.com/open-mmlab/mmdeploy/pull/34
=> [Enhancement] Download flake8 from github as pre-commit hooks

docs/en/datasets/det.md, docs/zh_cn/datasets/det.md
=> [Docs] Update docs link

setup.py
https://github.com/open-mmlab/mmcv/pull/1637
**Before PR**:
**After PR**:
=> Deprecate the support for 'python setup.py test'

configs/textrecog/sar/README.md
=> [Fix] Fix link of config

tools/data/textdet/ctw1500_converter.py
Extend ctw1500 converter to support text fields
Add text in annotions
=> Extend ctw1500 converter to support text fields

tools/data/textdet/totaltext_converter.py
Extend totaltext converter to support text fields
Add text in annotation.
=> Extend totaltext converter to support text fields

configs/kie/sdmgr/README.md, configs/ner/bert_softmax/README.md, configs/textdet/dbnet/README.md, configs/textdet/drrg/README.md, configs/textdet/fcenet/README.md, configs/textdet/maskrcnn/README.md, configs/textdet/panet/README.md, configs/textdet/psenet/README.md, configs/textdet/textsnake/README.md, configs/textrecog/abinet/README.md, configs/textrecog/crnn/README.md, configs/textrecog/nrtr/README.md, configs/textrecog/robust_scanner/README.md, configs/textrecog/sar/README.md, configs/textrecog/satrn/README.md, configs/textrecog/seg/README.md, configs/textrecog/tps/README.md, docs/en/stats.py, docs/zh_cn/stats.py
Update the config according to OpemMMLab's form-standard
=> [Docs] update readme according to standard

mmocr/utils/__init__.py, mmocr/utils/setup_env.py, tests/test_utils/test_setup_env.py, tools/test.py, tools/train.py
Add setup multi-processing both in train and test.
1. move setup_multi_processes to mmocr/utils/setep_env.py
2. add setup_multi_processes in tools/test.py
=> [Enhance]Add setup multi-processing both in train and test.

docs/en/testing.md, docs/en/training.md, mmocr/apis/train.py
Confidently support CPU training/testing after MMCV has fixed the bug https://github.com/open-mmlab/mmcv/pull/1621
Related PR:
https://github.com/open-mmlab/mmdetection/pull/7016
=> [Feature] Support CPU training/testing

tools/test.py
https://github.com/open-mmlab/mmocr/pull/603
=> [Enhancement] Remove unnecessary custom_import from test.py

.pre-commit-config.yaml, demo/ner_demo.py, mmocr/core/__init__.py, mmocr/core/deployment/deploy_utils.py, mmocr/datasets/__init__.py, mmocr/models/__init__.py, mmocr/models/common/__init__.py, mmocr/models/kie/__init__.py, mmocr/models/ner/__init__.py, mmocr/models/textdet/__init__.py, mmocr/models/textrecog/__init__.py, setup.cfg, setup.py, tests/test_core/test_deploy_utils.py, tools/deployment/mmocr_handler.py
1. Remove seed-isort-config in pre-commit hook
2. Upgrade isort to v5.10.1 (latest version)
3. Replace known_standard_library with extra_standard_library
https://github.com/open-mmlab/mmflow/pull/87
=> [Enhancement] Upgrade isort

docs/en/install.md, docs/zh_cn/install.md
MMOCR has different version requirements on its dependencies as its version changes. This PR adds a lookup table from which users can decide whether their MMCV and MMDetection version fits the requirement.
=> [Docs] Add detailed version requirement table

.pre-commit-config.yaml, mmocr/datasets/openset_kie_dataset.py, mmocr/models/common/detectors/__init__.py, mmocr/models/common/detectors/single_stage.py, mmocr/models/common/layers/__init__.py, mmocr/models/common/modules/__init__.py, mmocr/models/common/modules/transformer_module.py, mmocr/models/textdet/postprocess/drrg_postprocessor.py, mmocr/models/textrecog/encoders/satrn_encoder.py, mmocr/models/textrecog/recognizer/satrn.py, tools/data/kie/closeset_to_openset.py
These hooks can validate the format of readme files and ensure all code files have required copyright info.
=> [Enhancement] Add open-mmlab precommit hooks

README_zh-CN.md
Update the readme document url
=> Update README_zh-CN  document URL

mmocr/utils/fileio.py, tests/test_utils/test_textio.py, tools/data/textrecog/funsd_converter.py
Support saving with json in recognition converter
=> [feature] Support json in recognition converter

docs/en/index.rst, docs/en/tutorials/blank_recog.md, docs/en/tutorials/dataset_types.md, mmocr/datasets/utils/parser.py
Add warning info for LineStrParser while more than two blanks were detected
=> [Enhancement] Add warning info for LineStrParser

.owners.yml
=> [Enhancement] Deploy openmmlab-bot

docs/en/datasets/det.md, docs/en/datasets/recog.md
Update Instructions for New Data Converters
- `docs/en/datasets/det.md`
- `docs/en/datasets/recog.md`
=> [Docs] Update Instructions for New Data Converters

README.md, README_zh-CN.md
Brief installation instruction in README
Reference to https://github.com/open-mmlab/mmediting/pull/816
=> [Docs] Brief installation instruction in README

docs/en/datasets/recog.md
=> [Enchance] recog dataset doc

docs/en/datasets/det.md
We separate the directory structure section to the end of each dataset block for a better user experience.
=> [Docs] Reorganize the directory structure section in det.md

.circleci/config.yml, .github/workflows/build_pr.yml, .github/workflows/build_push.yml
Update Git Action to facilitate the following tests:
- Linting
- Ubuntu18.04 Py3.7 + Pt1.8.1 + cpu
- Ubuntu18.04 Py3.7 + Pt1.8.1 + cu102 (install and build only)
- Windows2022 Py3.7 + Pt1.8.1 + cpu/cu102
- Linting
- Ubuntu18.04 Py3.6/Py3.8/Py3.9 + Pt1.8.1 + cpu (Py3.10 may encounter dependency error)
- Ubuntu18.04 Py3.7 + [Pt1.5.1 - Pt1.11.0] + cpu    (latest Pt version up-to-date is Pt1.11.0)
- Ubuntu18.04 Py3.7 + Pt1.8.1 + cu102 (install and build only)
- Windows2022 Py3.7 + Pt1.8.1 + cpu/cu102
=> [Enhancement] Update Git Action

docs/en/datasets/det.md, docs/en/datasets/recog.md
=> [Doc] Update recog.md for lmdb Generation

.circleci/config.yml, .circleci/test.yml
Code tests are not required when only docs files are modified. This PR makes use of CircleCI's [Dynamic Config](https://circleci.com/docs/2.0/dynamic-config/) feature to skip the code tests conditionally.
=> [Enhancement] Skip CIs when docs are modified

.github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml
This PR unifies the test name styles and fixes a wrong path to ignore in tests on Github Action.
=> [Enhancement] Rename Github tests, fix ignored paths

README.md, README_zh-CN.md
=> [Docs] Add MMCV

.github/CONTRIBUTING.md
New contributors always get stuck by Ruby when preparing pre-commit hooks. This PR refines its installation instruction accordingly.
=> [Docs] Update CONTRIBUTING.md

docs/en/datasets/det.md, docs/en/datasets/recog.md, tools/data/textdet/totaltext_converter.py, tools/data/textrecog/totaltext_converter.py
1. To solve issue #940 
2. Fix some typos in docs
=> [Fix] Fix TotalText Anno version issue

mmocr/datasets/pipelines/dbnet_transforms.py, tests/test_dataset/test_dbnet_transforms.py
The current implementation of ImgAug transform transforms bounding box points [x1, y1, x2, y2] in the same way as keypoints, and the resulting keypoints [x3, y3, x4, y4] can break the basic assumptions in bounding boxes that (x4 > x3) and (y4 > y4). This PR transforms the bounding box in the right way to make sure the resulting box still bounds the instance region. It also handles the out-of-boundary bounding boxes by clipping out the invalid regions.
The same issue also exists in polygon transform. Treating a polygon as a collection of keypoints way too simplifies the assumption. The resulting polygons without boundary tests can cross the boundary and become noise data. This PR help clip the illegal regions as well.
Using this augmentation to train DBNet can slightly increase its …
=> [Fix] Fix ImgAug transform

docs/en/tutorials/config.md
Just a small fix of some typos and updates in `config.md`.
=> [Docs] Fix typos

configs/_base_/det_pipelines/dbnet_pipeline.py, configs/_base_/det_pipelines/drrg_pipeline.py, configs/_base_/det_pipelines/fcenet_pipeline.py, configs/_base_/det_pipelines/maskrcnn_pipeline.py, configs/_base_/det_pipelines/panet_pipeline.py, configs/_base_/det_pipelines/psenet_pipeline.py, configs/_base_/det_pipelines/textsnake_pipeline.py
=> [Fix] Remove confusing img_scales in pipelines

mmocr/models/textrecog/convertors/attn.py
Fix issues #1098  and #1092 
Add one line of code according to #1092
=> Fix #1098: normalize text recognition scores

configs/textdet/psenet/metafile.yml
=> [Fix] PSENet metafile

docs/en/install.md
=> links update

mmocr/datasets/base_dataset.py
Fixed issue #1150 : **docstring** syntax error of lineno 19 & 21
**Just** delete a space at line 19 and add code block at line 21
**Before PR**:
**After PR**:
=> Fixed docstring syntax error of line 19 & 21

configs/textrecog/abinet/base.py, mmocr/models/textrecog/decoders/abi_fuser.py, mmocr/models/textrecog/decoders/abi_language_decoder.py
=> [Fix] Fix abinet

configs/textdet/drrg/drrg_r50_fpn_unet_1200e_ctw1500.py
=> [Config] Fix drrg

docker/Dockerfile
Address https://github.com/open-mmlab/mmocr/issues/1177
=> [Fix] MMCV compatability due to outdated MMDet

configs/kie/sdmgr/README.md, configs/kie/sdmgr/metafile.yml, mmocr/utils/ocr.py, tests/test_utils/test_ocr.py
=> [Enhancement] Update links to SDMGR links

mmocr/evaluation/metrics/recog_metric.py
=> [Enchance] recog string metric

mmocr/utils/polygon_utils.py
=> [Fix] the left is_list_of

mmocr/models/common/losses/__init__.py, mmocr/models/common/losses/bce_loss.py, mmocr/models/textdet/heads/base_textdet_head.py, mmocr/models/textdet/heads/db_head.py, mmocr/models/textdet/module_losses/db_module_loss.py, mmocr/models/textdet/module_losses/drrg_module_loss.py, mmocr/models/textdet/module_losses/textsnake_module_loss.py, mmocr/models/textdet/postprocessors/base_postprocessor.py, mmocr/models/textdet/postprocessors/db_postprocessor.py, tests/test_models/test_common/test_losses/test_bce_loss.py, tests/test_models/test_textdet/test_heads/test_db_head.py, tests/test_models/test_textdet/test_module_losses/test_db_module_loss.py, tests/test_models/test_textdet/test_postprocessors/test_db_postprocessor.py
And update type hints in BaseTextDetPostprocessor
=> Use BCEWithLogitsLoss as many as possible for AMP

configs/textrecog/crnn/_base_crnn_mini-vgg.py, configs/textrecog/crnn/metafile.yml, configs/textrecog/tps/crnn_tps.py, configs/textrecog/tps/metafile.yml, mmocr/models/textrecog/backbones/__init__.py, mmocr/models/textrecog/backbones/mini_vgg.py, tests/test_models/test_textdet/test_wrappers/test_mmdet_wrapper.py, tests/test_models/test_textrecog/test_backbones/test_mini_vgg.py
=> [Fix] Rename VeryDeepVGG to MiniVGG

docs/en/get_started/quick_run.md, docs/zh_cn/get_started/quick_run.md
Not yet finished, need to be merged after Installation, Inference, and utilities are all merged.
=> [Docs] Quick run

configs/textdet/_base_/datasets/icdar2017.py, configs/textdet/dbnetpp/_base_dbnetpp_resnet50-dcnv2_fpnc.py, configs/textdet/psenet/_base_psenet_resnet50_fpnf.py, configs/textrecog/_base_/datasets/icdar2013.py, configs/textrecog/_base_/datasets/icdar2015.py, configs/textrecog/_base_/datasets/synthtext_add.py, configs/textrecog/abinet/_base_abinet-vision.py, configs/textrecog/robust_scanner/robustscanner_resnet31_5e_st-sub_mj-sub_sa_real.py, configs/textrecog/sar/sar_resnet31_parallel-decoder_5e_st-sub_mj-sub_sa_real.py, mmocr/datasets/dataset_wrapper.py, mmocr/models/textdet/detectors/base.py
=> Full regression testing fix

mmocr/__init__.py, requirements/readthedocs.txt
=> Bump version to 1.0.0rc0

.github/workflows/merge_stage_test.yml
=> [CI] Del CI support for torch 1.5.1

.github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml
=> [CI] Test windows cu111

docs/en/get_started/quick_run.md
=> [Docs] Fix quickrun

mmocr/models/textdet/detectors/mmdet_wrapper.py
Redefining `i` from outer loop
=> [Fix] Fix a bug in MMDetWrapper

mmocr/models/textrecog/convertors/attn.py, mmocr/models/textrecog/recognizer/abinet.py
Fix recognition socre #1332 issue caused by #1119
=> [Fix] Fix Recognition Score Normalization Issue

configs/textdet/maskrcnn/_base_mask-rcnn_resnet50_fpn.py
Simplify the Mask R-CNN config by inheriting from MMDet's config.
=> [Config] Simplify the Mask R-CNN config

tools/analysis_tools/browse_dataset.py
=> [Fix] Fix browse_dataset.py

docs/en/conf.py, docs/zh_cn/conf.py
=> [Docs] Add global notes to the docs and the version switcher menu

docs/en/conf.py, docs/zh_cn/conf.py
=> [Docs] Add version switcher to menu

docs/en/user_guides/inference.md, docs/zh_cn/user_guides/inference.md
=> [Docs] Fix inference docs

configs/textrecog/abinet/_base_abinet-vision.py, configs/textrecog/abinet/abinet_20e_st-an_mj.py, configs/textrecog/crnn/_base_crnn_mini-vgg.py, configs/textrecog/crnn/crnn_mini-vgg_5e_mj.py, configs/textrecog/master/_base_master_resnet31.py, configs/textrecog/master/master_resnet31_12e_st_mj_sa.py, configs/textrecog/nrtr/_base_nrtr_modality-transform.py, configs/textrecog/nrtr/_base_nrtr_resnet31.py, configs/textrecog/nrtr/nrtr_modality-transform_6e_st_mj.py, configs/textrecog/robust_scanner/_base_robustscanner_resnet31.py, configs/textrecog/robust_scanner/robustscanner_resnet31_5e_st-sub_mj-sub_sa_real.py, configs/textrecog/sar/_base_sar_resnet31_parallel-decoder.py, configs/textrecog/sar/sar_resnet31_parallel-decoder_5e_st-sub_mj-sub_sa_real.py, configs/textrecog/satrn/_base_satrn_shallow.py, configs/textrecog/satrn/satrn_shallow_5e_st_mj.py
Update the configs for text recognition models according to the latest regression benchmark settings.
=> [Config] Update rec configs

configs/_base_/recog_models/abinet.py, configs/_base_/recog_models/master.py, configs/_base_/recog_models/nrtr_modality_transform.py, configs/_base_/recog_models/robust_scanner.py, configs/_base_/recog_models/sar.py, configs/_base_/recog_models/satrn.py, configs/textrecog/abinet/abinet_vision_only_academic.py, configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py, configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py, configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py, configs/textrecog/sar/sar_r31_sequential_decoder_academic.py, configs/textrecog/satrn/satrn_academic.py, configs/textrecog/satrn/satrn_small.py
Fixes https://github.com/open-mmlab/mmocr/issues/1428
=> Remove max_seq_len inconsistency

docs/en/get_started/install.md, docs/en/notes/changelog.md, docs/zh_cn/get_started/install.md, mmocr/version.py
Merge after https://github.com/open-mmlab/mmocr/pull/1417, https://github.com/open-mmlab/mmocr/pull/1431, https://github.com/open-mmlab/mmocr/pull/1414, https://github.com/open-mmlab/mmocr/pull/1411
=> Bump version to 1.0.0rc1

docs/en/tutorials/config.md
To better use mmocr functionality.
It's a few lines modified to add more logger hooks to docs.
=> [Docs] Logger Hook Config Updated to Add WandB

README.md, README_zh-CN.md
Add MMYOLO in Readme.
If this PR introduces a new feature, it is better to list some use cases here, and update the …
=> [DOCs] Add MMYOLO in Readme.

.github/ISSUE_TEMPLATE/1-bug-report.yml, .github/ISSUE_TEMPLATE/2-feature_request.yml, .github/ISSUE_TEMPLATE/3-new-model.yml, .github/ISSUE_TEMPLATE/4-documentation.yml, .github/ISSUE_TEMPLATE/config.yml
The template lacks usage questions.
Add usage template
=> [Template] issue template

configs/textdet/dbnet/dbnet_resnet50-oclip_1200e_icdar2015.py, configs/textdet/dbnet/dbnet_resnet50_1200e_icdar2015.py, configs/textdet/dbnetpp/dbnetpp_resnet50-oclip_fpnc_1200e_icdar2015.py, configs/textdet/dbnetpp/dbnetpp_resnet50_fpnc_1200e_icdar2015.py, configs/textdet/drrg/drrg_resnet50-oclip_fpn-unet_1200e_ctw1500.py, configs/textdet/fcenet/fcenet_resnet50-oclip_fpn_1500e_ctw1500.py, configs/textdet/fcenet/fcenet_resnet50-oclip_fpn_1500e_icdar2015.py, configs/textdet/maskrcnn/mask-rcnn_resnet50-oclip_fpn_160e_ctw1500.py, configs/textdet/maskrcnn/mask-rcnn_resnet50-oclip_fpn_160e_icdar2015.py, configs/textdet/psenet/psenet_resnet50-oclip_fpnf_600e_ctw1500.py, configs/textdet/psenet/psenet_resnet50-oclip_fpnf_600e_icdar2015.py, configs/textdet/textsnake/textsnake_resnet50-oclip_fpn-unet_1200e_ctw1500.py
Add some text detection model configs using resnet-oclip as the backbone.
=> [Config] Add oCLIP configs

dataset_zoo/icdar2015/textdet.py, dataset_zoo/icdar2015/textrecog.py, mmocr/datasets/preparers/data_converter.py, mmocr/datasets/preparers/parsers/base.py, mmocr/datasets/preparers/parsers/icdar_txt_parser.py, mmocr/utils/__init__.py, mmocr/utils/bbox_utils.py, tests/test_utils/test_bbox_utils.py
1. add the removal of redundant strings
2. add a converter for different bounding box format
=> [Fix] Fix ICDARTxtParser

dataset_zoo/svtp/metafile.yml, dataset_zoo/svtp/sample_anno.md, dataset_zoo/svtp/textrecog.py
This PR relies on the updated `ICDARTxtTextRecogAnnParser` in #1529
=> [Feature] Add SVTP to dataset preparer

dataset_zoo/iiit5k/metafile.yml, dataset_zoo/iiit5k/sample_anno.md, dataset_zoo/iiit5k/textrecog.py
=> [Feature] iiit5k converter

mmocr/datasets/preparers/data_converter.py
=> [Fix] [DP] Automatically create nonexistent directory for base  configs

mmocr/datasets/preparers/dumpers/dumpers.py
=> [Fix] Wildreceipt tests

mmocr/utils/__init__.py, mmocr/utils/fileio.py, tests/test_utils/test_fileio.py
=> [Feature] Add get_md5

dataset_zoo/icdar2015/textrecog.py
=> [Config] Support IC15_1811 

tools/train.py
It's slightly different from
https://github.com/open-mmlab/mmdetection/blob/4365f5eb906bf81c2296b2a5960bdb1f562427d4/tools/train.py#L96-L106
=> [Fix] Auto scale lr

mmocr/datasets/preparers/parsers/base.py, tests/test_datasets/test_preparers/test_parsers/test_icdar_txt_parsers.py
=> [Fix] fix icdar data parse for text containing seperator

mmocr/apis/inferencers/base_mmocr_inferencer.py, mmocr/apis/inferencers/kie_inferencer.py, mmocr/apis/inferencers/mmocr_inferencer.py, mmocr/apis/inferencers/textdet_inferencer.py, mmocr/apis/inferencers/textrec_inferencer.py
Fixes https://github.com/open-mmlab/mmengine/issues/736
=> [Fix] Keep E2E Inferencer output simple

docs/en/conf.py, docs/zh_cn/conf.py
=> [Fix] Remove outdated tutorial link

mmocr/models/textrecog/decoders/__init__.py, mmocr/models/textrecog/decoders/aster_decoder.py, tests/test_models/test_textrecog/test_decoders/test_aster_decoder.py
=> [ASTER] Add ASTER decoder

mmocr/datasets/transforms/__init__.py, mmocr/datasets/transforms/wrappers.py, tests/test_datasets/test_transforms/test_wrappers.py
=> [Transform] ConditionApply

projects/ABCNet/README.md
=> [Docs] updata abcnet doc

docker/Dockerfile
=> [Fix] Update dockerfile

README.md, README_zh-CN.md, projects/ABCNet/README_V2.md, projects/ABCNet/abcnet/model/__init__.py, projects/ABCNet/abcnet/model/abcnet_rec_backbone.py, projects/ABCNet/abcnet/model/bifpn.py, projects/ABCNet/abcnet/model/coordinate_head.py, projects/ABCNet/abcnet/model/rec_roi_head.py, projects/ABCNet/config/abcnet_v2/_base_abcnet-det_resnet50_fpn.py, projects/ABCNet/config/abcnet_v2/_base_abcnet-v2_resnet50_bifpn.py, projects/ABCNet/config/abcnet_v2/abcnet-v2_resnet50_bifpn_500e_icdar2015.py, projects/ABCNet/config/abcnet_v2/abcnet_resnet50_fpn.py
=> abcnetv2 inference

mmocr/datasets/ocr_dataset.py
A minor mistake, but easily causes some trouble.
=> [Fix] Fix a minor error in docstring

docs/en/user_guides/data_prepare/dataset_preparer.md, docs/en/user_guides/data_prepare/det.md, docs/en/user_guides/data_prepare/kie.md, docs/en/user_guides/data_prepare/recog.md, docs/zh_cn/user_guides/data_prepare/dataset_preparer.md, docs/zh_cn/user_guides/data_prepare/det.md, docs/zh_cn/user_guides/data_prepare/kie.md, docs/zh_cn/user_guides/data_prepare/recog.md
=> [Docs] Remove unsupported datasets in docs

configs/kie/sdmgr/_base_sdmgr_unet16.py, mmocr/apis/inferencers/base_mmocr_inferencer.py, mmocr/apis/inferencers/kie_inferencer.py, mmocr/ocr.py, tests/test_apis/test_inferencers/test_textdet_inferencer.py, tests/test_apis/test_inferencers/test_textrec_inferencer.py
1. Fixes wrong visualization color due to incorrect channel order
2. Temporarily fixes wrong image size in KIE visualization
3. Update unit tests
=> [Fix] Fix some inferencer bugs

tools/dataset_converters/textdet/ilst_converter.py
Fixed typo.
splited -> splitted
**Before PR**:
**After PR**:
=> Fix typo in ilst_converter.py

mmocr/models/textrecog/decoders/aster_decoder.py
=> [Fix] Add missing softmax in ASTER forward_test

mmocr/datasets/preparers/parsers/icdar_txt_parser.py
=> [Fix] icdar textrecog ann parser skip data with ignore flag

docs/en/basic_concepts/evaluation.md, docs/zh_cn/basic_concepts/evaluation.md
Fix docs recog CharMetric P/R error definition
**Before PR**:
**After PR**:
=> Fix docs recog CharMetric P/R error definition

projects/SPTS/README.md
=> [Fix] SPTS readme

docs/en/notes/changelog.md
=> Fix changelog

mmocr/utils/ocr.py
=> correct word spelling

docs/en/api/transforms.rst, docs/en/basic_concepts/transforms.md, docs/zh_cn/api/transforms.rst, docs/zh_cn/basic_concepts/transforms.md
=> [Doc] Remove LoadImageFromLMDB from docs

configs/textdet/psenet/metafile.yml
=> [Fix] Add pse weight to metafile

dataset_zoo/synthtext/metafile.yml, dataset_zoo/synthtext/textspotting.py
=> [Fix] Synthtext metafile

mmocr/datasets/preparers/obtainers/naive_data_obtainer.py
执行mapping时如果对象是单个文件，并且目标目录有多层结构，则会导致运行shutil.move(src, dst)时触发报错，例如：
['zh_train.json', 'annotations/zh/ner_train.json']
If this PR introduces a new feature, it is better to list some use cases here, and update the …
=> [Bug] if dst not exists, when move a single file may raise a file not exsits error.

docs/en/get_started/faq.md
=> [Docs] Update faq

README.md, README_zh-CN.md
[doc]:add more social network links
README.md and README_zh-CN.md
**Before PR**:
**After PR**:
=> [doc]:add more social network links

mmocr/apis/inferencers/base_mmocr_inferencer.py
=> [Fix] Revert sync bn in inferencer

mmocr/__init__.py
=> [Fix] Fix mmdet digit version

.github/ISSUE_TEMPLATE/1-bug-report.yml, docs/en/conf.py, docs/zh_cn/conf.py
=> [Docs] Remove version tab

.circleci/test.yml
=> [CI] Switched branches

.circleci/test.yml, .github/workflows/merge_stage_test.yml, .github/workflows/pr_stage_test.yml, .pre-commit-config.yaml, mmocr/datasets/pipelines/box_utils.py, mmocr/datasets/pipelines/textdet_targets/fcenet_targets.py, mmocr/models/textdet/postprocess/utils.py, requirements/runtime.txt
=> [CI] Fix 0.x tests

dataset_zoo/iiit5k/textrecog.py
=> [Fix] Update iiit5k md5

docs/en/device/npu.md, docs/zh_cn/device/npu_zh.md
Add NPU result.
Add docs/en/device/npu.md, add docs/zh_CN/device/npu.md.
None.
None.
**Before PR**:
**After PR**:
=> [Docs] Add NPU support page

mmocr/apis/inferencers/mmocr_inferencer.py, mmocr/datasets/preparers/dumpers/json_dumper.py
=> [Fix] fix some Chinese display problems.

mmocr/models/textdet/detectors/mmdet_wrapper.py
=> [Update] Fix MaskRCNN bug

configs/textrecog/abinet/README.md, configs/textrecog/abinet/abinet-vision_10e_union14m.py, configs/textrecog/aster/README.md, configs/textrecog/aster/aster_resnet45_6e_union14m.py, configs/textrecog/nrtr/README.md, configs/textrecog/nrtr/nrtr_resnet31-1by8-1by4_union14m.py, configs/textrecog/sar/README.md, configs/textrecog/sar/sar_resnet31_sequential-decoder_5e_union14m.py, configs/textrecog/satrn/README.md, configs/textrecog/satrn/satrn_shallow_5e_union14m.py
Add configs and README for five models
=> [MODEL] Add Union14M trained models

README.md, README_zh-CN.md, configs/textrecog/_base_/datasets/union14m_benchmark.py, configs/textrecog/_base_/datasets/union14m_train.py, configs/textrecog/_base_/schedules/schedule_adamw_cos_10e.py, configs/textrecog/maerec/README.md, configs/textrecog/maerec/_base_marec_vit_s.py, configs/textrecog/maerec/maerec_b_union14m.py, configs/textrecog/maerec/maerec_s_union14m.py, configs/textrecog/maerec/metafile.yml, mmocr/models/textrecog/backbones/__init__.py, mmocr/models/textrecog/backbones/vit.py, mmocr/models/textrecog/decoders/__init__.py, mmocr/models/textrecog/decoders/maerec_decoder.py, mmocr/models/textrecog/recognizers/__init__.py, mmocr/models/textrecog/recognizers/maerec.py, model-index.yml, requirements/runtime.txt
Migrate MAERec code from https://github.com/Mountchicken/Union14M
=> [MODEL] Add MAERec

README.md, README_zh-CN.md
Add OpenXLab Badge to share official applications, community applications and ecological applications based on MMOCR in the OpenXLab platform.
Added OpenXLab Badge in ReadME（English & Chinese）
If this PR introduces a new feature, it is better to list some use cases here, and …
=> Add OpenXLab Badge
